# for now, just specify "setuptools" as the build system
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# it is unclear whether toml can support both "setup.cfg" and "setup.py"
